name: Release

on:
  release:
    types: [released]

jobs:
  build-upload:
    name: Build and upload to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required for pypi upload
      contents: read # required for checkout

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build stubs
        run: |
          pip install mypy
          stubgen --include-docstrings src/ -o src/

      - name: Build wheels
        run: |
          pip install build
          python3 -m build --wheel

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
