name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.12"]
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - uses: actions/checkout@v4

      - name: Test with tox
        run: |
          pip install tox
          tox -- --cov npx --cov-report xml --cov-report term

      - name: Submit to codecov
        uses: codecov/codecov-action@v4
        if: ${{ matrix.python-version == '3.9' }}
